e main.h
vsplit main.c
tabnew modules/moteur/moteur.h
vsplit modules/moteur/moteur.c
tabnew modules/graphique/graphique.h
vsplit modules/graphique/graphique.c
tabnew module/sonore/sonore.h
vsplit module/sonore/sonore.c
tabnew modules/IA/IA.h
vsplit modules/IA/IA.c
tabnew modules/reseau/reseau.h
vsplit modules/reseau/reseau.c
