e main.h
vsplit main.c
tabnew moteur/struct_jeu.c
vsplit moteur/struct_case_joueur.c
tabnew moteur/moteur.h
vsplit moteur/moteur.c
tabnew graphique/TERM/graphique_TERM.h
vsplit graphique/TERM/graphique_TERM.c
tabnew IA/IA.h
vsplit IA/IA.c
tabnew systeme/systeme.h
vsplit systeme/systeme.c
tabnew inSecure/inSecure.h
vsplit inSecure/inSecure.c
tabnew TODO.mkd
